CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255)                            NOT NULL UNIQUE,
    email     VARCHAR(255)                            NOT NULL UNIQUE,
    password  VARCHAR(255)                            NOT NULL,
    verified  BOOLEAN                                 NOT NULL DEFAULT FALSE,
    authority SMALLINT                                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);