x-database-variables: &db-variables
  POSTGRES_DB: javagas
  POSTGRES_USER: api
  POSTGRES_PASSWORD: secret
x-spring-database-variables: &spring-db-variables
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/javagas
  SPRING_DATASOURCE_USERNAME: api
  SPRING_DATASOURCE_PASSWORD: secret
services:
  client:
    image: rickallan/javagas-client:latest
    container_name: "javagas-client"
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    mem_limit: 256m
  server:
    image: rickallan/javagas-server:latest
    container_name: "javagas-server"
    ports:
      - '8080:8080'
    environment:
      <<: *spring-db-variables
    networks:
      - default
    mem_limit: 512m
  postgres:
    image: 'postgres:latest'
    container_name: "postgres"
    environment:
      <<: *db-variables
    ports:
      - '5432:5432'
    networks:
      - default
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    mem_limit: 512m
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: "prometheus"
    ports:
      - '9090:9090'
    networks:
      - default
    volumes:
      - ./server/javagas/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    mem_limit: 128m
  grafana:
    image: 'grafana/grafana:latest'
    container_name: "grafana"
    ports:
      - '3500:3000'
    networks:
      - default
    mem_limit: 128m

networks:
  default:
    driver: bridge

volumes:
  pg-db-data:
