spring:
  application:
    name: JaVagas
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/javagas_db}
    username: ${POSTGRES_USER:javagas_user}
    password: ${POSTGRES_PASSWORD:000000}
  flyway:
    enabled: true
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/javagas_db}
    user: ${POSTGRES_USER:javagas_user}
    password: ${POSTGRES_PASSWORD:000000}
    locations: classpath:db/migrations/postgresql
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
logging.level.org.hibernate.SQL: DEBUG
springdoc.api-docs.path: /api/docs
server.forward-headers-strategy: framework
management:
  endpoints:
    web.exposure.include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: JaVagas
    version: 1.0.0
    description: API for managing job vacancies
    github: https://github.com/allan-rcos/javagas
    bitbucket: https://bitbucket.org/allan-rcos/javagas
  java:
    version: ${java.version}
  spring:
    version: ${spring.version}
  build:
    time: ${maven.build.timestamp}
    user: ${user.name}
    host: ${host.name}