spring:
  application:
    name: JaVagas
  datasource:
    url: jdbc:postgresql://postgres:5432/javagas
    username: api
    password: secret
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
logging.level.org.hibernate.SQL: DEBUG
management:
  endpoints:
    web.exposure.include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: JaVagas
    version: 1.0.0
    description: API for managing job vacancies
    github: https://github.com/allan-rcos/javagas
    bitbucket: https://bitbucket.org/allan-rcos/javagas
  java:
    version: ${java.version}
  spring:
    version: ${spring.version}
  build:
    time: ${maven.build.timestamp}
    user: ${user.name}
    host: ${host.name}
springdoc:
  api-docs:
    path: /api/docs
server:
  forward-headers-strategy: framework